services:
  kafka:
    image: apache/kafka:latest #image
    container_name: kafka-rag
    hostname: kafka
    ports:
      - "9092:9092" #port for the clients
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller' #node operate as broker and controller
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093' #portf for docker containers communications
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # mock
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 #mock
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 #mock
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    healthcheck: #healthcheck
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"] # topic list bootstrap
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  ksqldb-server: 
    image: confluentinc/ksqldb-server:0.29.0
    container_name: ksqldb-server
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8088:8088" # client port for the db 
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "kafka:29092" #connect to kafka through INTERNAL 
      KSQL_KSQL_SERVICE_ID: "ksql_rag_telemetry_processor"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
    healthcheck: #Healthcheck
      test: ["CMD-SHELL", "nc -z localhost 8088 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 15s

  ksqldb-init:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: ksqldb-init
    depends_on:
      ksqldb-server:
        condition: service_healthy
    volumes:
      - ./init.sql:/tmp/init.sql #map the sql 
    entrypoint: [ "/bin/sh", "-c" ]
    command: # inject the sql code for the aggragation
      - |
        echo "ksqldb-server ok inject the init.sql plicy" 
        ksql http://ksqldb-server:8088 --file /tmp/init.sql
        echo "Policy ok!"
